export const texts = {
  logoAlt: 'Imagem de Logo do CESAR School',
  googleLogoAlt: 'Imagem Google Botão de Login',
  welcomeText: 'Bem-vindo ao Researcher Dashboard',
  signOut: 'Sair',
  continueWithYourCesarAccount: 'Continue com sua conta CESAR',
  profilePhotoAlt: 'Foto de perfil',
  yourResearchList: 'Sua Lista de Pesquisas',
  generalResearchList: 'Lista de pesquisa geral',
  helloResearcher: 'Olá,',
  confirmYourProfileInfoMessage:
    'Por favor, confirme as informações do seu perfil para nos ajudar a buscar seus dados no Lattes.',
  displayName: 'Seu nome',
  email: 'Seu email',
  lattesUrl: 'Seu currículo Lattes',
  lattesUrlPlaceholder: 'ex: http://lattes.cnpq.br/0000000000000',
  aliases: 'Como referenciam você em publicações',
  addNew: 'Adicionar',
  inputAndPressEnterOrTab:
    'Caso não encontre o que procura, por favor digite e pressione enter ou tab para confirmar.',
  submitConfirmation: 'Confirmar',
  articleYearlyChart: 'Publicações Totais por Ano',
  topPublishersYear: 'Publicações por Autores',
  titlesMostRepeated: 'Expressões mais Frequentes nos Títulos',
  researchTypeDistribution: 'Distribuição de Tipos de Pesquisa',
  totalOfResearches: 'Total de Trabalhos',
  articles: 'Artigos',
  publishType: 'Tipos de Publicação',
  mainAuthors: 'Autores Principais',
  addPublish: 'Adicionar Publicação',
  submitAddPublish: 'Confirmar',
  title: 'Título',
  titleDescription:
    'Por favor, tente colocar o mais próximo do que está cadastrado no seu Lattes.',
  coAuthorsLabel: 'Co-Autores da publicação',
  publishTypeLabel: 'Tipo de Publicação',
  publishAreaLabel: 'Área de Publicação',
  mainAuthorFlag: 'Sou o autor principal desta publicação',
  placeOfPublishLabel: 'Onde foi Publicado',
  doiUrlLabel: 'Link para o Doi',
  issnNumberLabel: 'Nº ISSN',
  publishYear: 'Ano da Publicação',
  cancel: 'Cancelar',
  clickHereToCheck: 'Clique aqui para checar o seu Lattes',
  select: 'Selecione...',
  addPublishSuccess: 'Publicação adicionada com sucesso!',
};
