export const texts = {
  logoAlt: 'Imagem de Logo do CESAR School',
  googleLogoAlt: 'Imagem Google Botão de Login',
  welcomeText: 'Bem-vindo ao Researcher Dashboard',
  signOut: 'Sair',
  continueWithYourCesarAccount: 'Continue com sua conta CESAR',
  profilePhotoAlt: 'Foto de perfil',
  yourResearchList: 'Sua Lista de Pesquisas',
  generalResearchList: 'Lista de pesquisa geral',
  helloResearcher: 'Olá,',
  confirmYourProfileInfoMessage:
    'Por favor, confirme as informações do seu perfil para nos ajudar a buscar seus dados no Lattes.',
  displayName: 'Seu nome',
  email: 'Seu email',
  lattesUrl: 'Seu currículo Lattes',
  lattesUrlPlaceholder: 'ex: http://lattes.cnpq.br/0000000000000',
  aliases: 'Como referenciam você em publicações',
  addNewAlias: 'Adicionar',
  inputAndPressEnterOrTab: 'Digite e pressione enter ou tab para confirmar.',
  submitConfirmation: 'Confirmar',
};
